"use client";
import "./globals.css";

import BeforeFooter from "@/components/BeforeFooter";
import Footer from "@/components/Footer";

import { Provider } from "react-redux";
import store from "./redux/store";
// fonts
import { Playfair_Display, Montserrat } from "next/font/google";
const playfair = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-playfair",
});
const mont = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` ${playfair.className} ${mont.className}`}>
      <body>
        <Provider store={store}>
          {children}
          <BeforeFooter />
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
