export const ActionTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
  REMOVE_ITEM: "REMOVE_ITEM",
  TO_EMPTY_CART: "TO_EMPTY_CART",
  GET_CART_COUNT: "GET_CART_COUNT",
};
